In [1]:
import numpy as np

In [5]:
np.__version__

'2.2.5'

## Create & Read

#### 1D Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape #No. of elements, why , in (5,) beacause in array if you dont have element more than value you have to ,

(5,)

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.ndim #diamentional of array will return

1

In [9]:
arr.size

5

#### 2D Array

In [10]:
arr2 = np.array([[1, 4, 5],[6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape  #(row, column) 

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.size

6

#### 3D Array

In [17]:
arr3 = np.array([[[1, 4, 5],[6, 7, 4]], [[7, 2, 9], [2, 7, 1]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[7, 2, 9],
        [2, 7, 1]]])

In [7]:
arr3.ndim

3

In [8]:
arr3.shape

(2, 2, 3)

In [9]:
arr4 = np.array([[[1, 4, 5],[6, 7, 4], [1, 4, 5]]])
arr4

array([[[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]]])

In [10]:
arr4.shape

(1, 3, 3)

In [11]:
arr4.ndim

3

In [12]:
arr4.size

9

### Create Randam array

In [7]:
randamArr = np.random.rand(3, 2, 3)
randamArr

array([[[0.18791743, 0.34128842, 0.05374111],
        [0.60140871, 0.53162381, 0.89865408]],

       [[0.27009525, 0.85206495, 0.73678853],
        [0.73002582, 0.79226837, 0.5513959 ]],

       [[0.33480787, 0.77108736, 0.5606884 ],
        [0.22771162, 0.32590256, 0.03475641]]])

In [8]:
randamArr.dtype

dtype('float64')

In [2]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
replaceNum = np.full((3, 2, 3), 8) #Replace numbers with any number
replaceNum

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [16]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[7, 2, 9],
        [2, 7, 1]]])

In [26]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [27]:
arr3[1]

array([[7, 2, 9],
       [2, 7, 1]])

In [29]:
arr3[1][0][1]

np.int64(2)

In [31]:
arr3[0:1]  #less than 1 rows will display 0th row will only display

array([[[1, 4, 5],
        [6, 7, 4]]])

In [32]:
arr3[-1]  #last index of an array

array([[7, 2, 9],
       [2, 7, 1]])

In [33]:
arr3[1, 0, 1]   #similar like arr3[1][0][1]

np.int64(2)

### Update & Delete

In [2]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [3]:
a1

array([[[0.9247233 , 0.81256356],
        [0.16550879, 0.01757962],
        [0.27099991, 0.82270737]],

       [[0.18206741, 0.62296074],
        [0.86043485, 0.36688849],
        [0.58152381, 0.29642244]]])

In [4]:
a2

array([[[0.97384046, 0.64074643],
        [0.82496242, 0.75386875],
        [0.31860072, 0.25536325]],

       [[0.84106381, 0.57698172],
        [0.53847228, 0.88569062],
        [0.08005566, 0.99411587]]])

#### Basic Math Operations

In [5]:
np.add(a1, a2)

array([[[1.89856376, 1.45330999],
        [0.99047121, 0.77144837],
        [0.58960063, 1.07807062]],

       [[1.02313122, 1.19994246],
        [1.39890714, 1.25257911],
        [0.66157947, 1.29053831]]])

In [6]:
np.subtract(a1, a2)

array([[[-0.04911716,  0.17181714],
        [-0.65945362, -0.73628914],
        [-0.04760081,  0.56734412]],

       [[-0.6589964 ,  0.04597903],
        [ 0.32196257, -0.51880213],
        [ 0.50146815, -0.69769343]]])

In [7]:
np.divide(a1, a2)

array([[[0.94956344, 1.26815153],
        [0.20062586, 0.0233192 ],
        [0.85059416, 3.22171407]],

       [[0.21647276, 1.07968888],
        [1.59791856, 0.41424001],
        [7.26399351, 0.29817695]]])

In [8]:
np.multiply(a1, a2)

array([[[0.90053297, 0.5206472 ],
        [0.13653854, 0.01325272],
        [0.08634077, 0.21008923]],

       [[0.15313031, 0.35943696],
        [0.46332032, 0.32494969],
        [0.04655427, 0.29467825]]])

#### Statastical Operations

In [14]:
sqrt = np.sqrt(25)
abs = np.abs(-2) #return positive number
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [10]:
sqrt

np.float64(5.0)

In [11]:
abs

np.int64(2)

In [12]:
power

np.int64(256)

In [13]:
log

np.float64(3.2188758248682006)

In [15]:
mins

np.float64(0.01757961508381045)

In [16]:
maxs

np.float64(0.9941158675165859)

#### Update 

In [18]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[7, 2, 9],
        [2, 7, 1]]])

In [19]:
arr3[0,0,2] = 500

In [20]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  7,   2,   9],
        [  2,   7,   1]]])

In [21]:
arr3.sort()

In [22]:
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  2,   7,   9],
        [  1,   2,   7]]])

In [25]:
arr3_reshape = arr3.reshape((3,2,2))
arr3_reshape

array([[[  1,   4],
        [500,   4]],

       [[  6,   7],
        [  2,   7]],

       [[  9,   1],
        [  2,   7]]])

### Appending & Inserting

In [3]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
append_array = np.append(zeroes, new_array, axis=0)   #axis=0 means row and axis=1 means column
append_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### Insert

In [9]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)   #after zeroes index 1 is row of array
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [13]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.51947143, 0.23416078, 0.79130262],
        [0.00408857, 0.41833022, 0.70560662]],

       [[0.10028143, 0.02790875, 0.49093635],
        [0.55684926, 0.83117869, 0.5726443 ]],

       [[0.20872846, 0.03195475, 0.99754594],
        [0.7289946 , 0.85205343, 0.96098695]]])

In [16]:
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.00408857, 0.41833022, 0.70560662]],

       [[0.55684926, 0.83117869, 0.5726443 ]],

       [[0.7289946 , 0.85205343, 0.96098695]]])

In [17]:
np.save("new_array", arr5)

In [18]:
np.load("new_array.npy")

array([[[0.00408857, 0.41833022, 0.70560662]],

       [[0.55684926, 0.83117869, 0.5726443 ]],

       [[0.7289946 , 0.85205343, 0.96098695]]])